# Generated by Django 2.1.1 on 2019-09-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=False, verbose_name='Публиковать')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Название слайда')),
                ('image', models.ImageField(height_field=100, upload_to=None, verbose_name='Изображение слайда', width_field=150)),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('link_text', models.CharField(max_length=50, null=True, verbose_name='Текст ссылки')),
                ('link', models.URLField()),
            ],
        ),
    ]
