# Generated by Django 2.1.1 on 2019-09-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Longgrid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, null=True, unique=True, verbose_name='uri')),
                ('public', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('date_pub', models.DateTimeField()),
                ('title', models.CharField(max_length=150, null=True, verbose_name='Название Лонггрида')),
                ('sumbol_cod', models.CharField(max_length=150, null=True, verbose_name='Символьный код Лонггрида')),
            ],
        ),
        migrations.RemoveField(
            model_name='slider',
            name='image',
        ),
        migrations.AlterField(
            model_name='slider',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
    ]
