# Generated by Django 2.1.1 on 2019-09-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190904_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='LonggridTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, unique=True, verbose_name='Тэг франшизы')),
                ('slug', models.SlugField(help_text='Поле задает уникалный адрес объекта в разделе сайта', null=True, unique=True, verbose_name='uri')),
            ],
        ),
        migrations.RemoveField(
            model_name='longgrid',
            name='sumbol_cod',
        ),
        migrations.AddField(
            model_name='longgrid',
            name='detail_image',
            field=models.ImageField(null=True, upload_to=None, verbose_name='Детальное изображение'),
        ),
        migrations.AddField(
            model_name='longgrid',
            name='image',
            field=models.ImageField(null=True, upload_to='media/', verbose_name='Изображение для превью'),
        ),
        migrations.AddField(
            model_name='slider',
            name='image',
            field=models.ImageField(null=True, upload_to='media/', verbose_name='Изображение слайда'),
        ),
        migrations.AddField(
            model_name='slider',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='Номер для сортировки'),
        ),
        migrations.AlterField(
            model_name='longgrid',
            name='public',
            field=models.BooleanField(default=False, null=True, verbose_name='Опубликовать'),
        ),
        migrations.AlterField(
            model_name='longgrid',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='uri'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='longgrid',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.LonggridTag', verbose_name='Теги статьи'),
        ),
    ]
