# Generated by Django 2.1.1 on 2019-09-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190908_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longgrid',
            name='date_pub',
            field=models.DateTimeField(verbose_name='Создан'),
        ),
    ]
