# Generated by Django 2.1.1 on 2019-09-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190908_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longgrid',
            name='detail_image',
            field=models.ImageField(null=True, upload_to='media/', verbose_name='Детальное изображение'),
        ),
    ]
