# Generated by Django 2.1.1 on 2019-09-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190908_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longgrid',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='Longgrid', to='blog.LonggridTag', verbose_name='Теги статьи'),
        ),
    ]
