# Generated by Django 2.1.1 on 2019-09-14 11:26

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190911_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='longgrid',
            name='short_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Редактор статей'),
        ),
    ]
