# Generated by Django 2.1.1 on 2019-09-14 11:28

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_longgrid_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='longgrid',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Полное описание статьи'),
        ),
        migrations.AlterField(
            model_name='longgrid',
            name='short_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Короткое описание статьи'),
        ),
    ]
