# Generated by Django 2.1.1 on 2019-09-15 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190914_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='longgrid',
            options={'verbose_name': 'Лонггрид', 'verbose_name_plural': 'Лонггриды'},
        ),
        migrations.RemoveField(
            model_name='longgrid',
            name='tags',
        ),
        migrations.DeleteModel(
            name='LonggridTag',
        ),
    ]
