# Generated by Django 2.1.1 on 2019-09-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190915_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='LonggridTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, unique=True, verbose_name='Тэг франшизы')),
                ('slug', models.SlugField(help_text='Поле задает уникалный адрес объекта в разделе сайта', null=True, unique=True, verbose_name='uri')),
            ],
        ),
        migrations.AddField(
            model_name='longgrid',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='Longgrid', to='blog.LonggridTag', verbose_name='Теги статьи Longgrid'),
        ),
    ]
