# Generated by Django 2.1.1 on 2019-09-16 16:17

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190915_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='LonggridPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='uri')),
                ('public', models.BooleanField(default=False, null=True, verbose_name='Опубликовать')),
                ('date_pub', models.DateTimeField(blank=True, verbose_name='Создан')),
                ('image', models.ImageField(null=True, upload_to='media/', verbose_name='Изображение для превью')),
                ('short_description', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Короткое описание статьи')),
                ('detail_image', models.ImageField(null=True, upload_to='media/', verbose_name='Детальное изображение')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Полное описание статьи')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
