# Generated by Django 2.1.1 on 2019-09-16 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_longgridpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LonggridPage',
        ),
    ]
