# Generated by Django 2.1.1 on 2019-09-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_delete_longgridpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longgrid',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='longgrid', to='blog.LonggridTag', verbose_name='Теги статьи Longgrid'),
        ),
    ]
