# Generated by Django 2.1.1 on 2019-09-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190918_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longgrid',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='Longgrids', to='blog.LonggridTag', verbose_name='Теги статьи Longgrid'),
        ),
    ]
