# Generated by Django 2.1.1 on 2019-09-24 18:11

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20190918_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='NBA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='uri')),
                ('public', models.BooleanField(default=False, null=True, verbose_name='Опубликовать')),
                ('date_pub', models.DateTimeField(blank=True, verbose_name='Создан')),
                ('image', models.ImageField(null=True, upload_to='media/', verbose_name='Изображение для превью')),
                ('short_description', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Короткое описание статьи')),
                ('detail_image', models.ImageField(null=True, upload_to='media/', verbose_name='Детальное изображение')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Полное описание статьи')),
                ('title', models.CharField(max_length=150, null=True, verbose_name='Название статьи NBA')),
            ],
            options={
                'verbose_name': 'NBA',
                'verbose_name_plural': 'NBAs',
            },
        ),
        migrations.CreateModel(
            name='NBATag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, unique=True, verbose_name='Тэг франшизы')),
                ('slug', models.SlugField(help_text='Поле задает уникалный адрес объекта в разделе сайта', null=True, unique=True, verbose_name='uri')),
            ],
        ),
        migrations.AlterField(
            model_name='longgridtag',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Тэг лонггрида'),
        ),
        migrations.AddField(
            model_name='nba',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='nba', to='blog.LonggridTag', verbose_name='Теги статьи NBA'),
        ),
    ]
