# Generated by Django 2.1.1 on 2019-09-24 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20190924_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='longgrid',
            name='detail_image',
        ),
        migrations.RemoveField(
            model_name='nba',
            name='detail_image',
        ),
    ]
