# Generated by Django 2.1.1 on 2019-09-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20190924_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longgrid',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Изображение для превью'),
        ),
        migrations.AlterField(
            model_name='nba',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Изображение для превью'),
        ),
        migrations.AlterField(
            model_name='nbatag',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Тэг NBA111'),
        ),
    ]
