# Generated by Django 2.1.1 on 2019-09-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20190926_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nba',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='nba', to='blog.NBATag', verbose_name='Теги статьи NBA'),
        ),
        migrations.AlterField(
            model_name='nbatag',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Тэг NBA'),
        ),
    ]
