# Generated by Django 2.1.1 on 2019-09-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20190926_1958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='longgridtag',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='nbatag',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='nba',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='NBA', to='blog.NBATag', verbose_name='Теги статьи NBA'),
        ),
    ]
